# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\rukarlie\Documents\Python\ChannelVariator\sndspdDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog:QtWidgets.QDialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(388, 138)
        #icon = QtGui.QIcon()
        #icon.addPixmap(QtGui.QPixmap(":/icons/icons/sndspdIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        #Dialog.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 90, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 211, 16))
        self.label.setObjectName("label")
        self.inLine = QtWidgets.QLineEdit(Dialog)
        self.inLine.setGeometry(QtCore.QRect(110, 50, 210, 20))
        self.inLine.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inLine.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inLine.setObjectName("inLine")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog:QtWidgets.QDialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle( "Окно ввода данных")
        #Dialog.setWhatsThis(_translate("Dialog", "Окно ввода скорости звука для дальнейших расчётов"))
        self.label.setText(_translate("Dialog", "Введите :"))
        #self.sndSpd.setStatusTip(_translate("Dialog", "Введите скорость звука в км/с"))
        #self.sndSpd.setWhatsThis(_translate("Dialog", "Поле для ввода скорости звука"))
        self.inLine.setText(_translate("Dialog", ""))
#import icons_res_rc
